### ISSUE TITLE
Suggestion for compounds capable of penetrating fungal grains

### ISSUE THREAD

**Issue by rosalynclz** [OpenSourceMycetoma/Series-1-Fenarimols#23]
Based on the input received from [#22 ] and data from the [Master List](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=1872217356), so far there were only **19 compounds tested** in the _Galleria mellonella_ larvae model, 14 of which were tested at fixed concentration of 20microM/larvae and the remaining 5 (6 if including posaconazole) were tested at various human pharmacokinetic equivalent dosages from [here](https://academic.oup.com/mmy/article/56/4/469/4158469). 
![image](https://user-images.githubusercontent.com/56122898/68544527-e9881a00-03bb-11ea-865f-63e90baaa464.png)

(Awaiting new data: https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/22#issuecomment-544381986)

The in vivo efficacy for the former 14 compounds are shown in the graph below. Based on the identified correlation in lipophilicity and in vivo efficacy (r = ˗ 0.722, p= 0.002, n= 14, one-tailed), aiming for a low LogD (e.g. ≤ 2.0) should be a design/selection criterion (e.g. compounds with LogD ≤ 2.0 from [OSN Target List ](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/blob/master/OSN_P4%20MycetOS%20lists.zip) yet to be synthesised: P4_C_MXF003, P4_D_MXF004, P4_A_010, P4_A_007)

![image](https://user-images.githubusercontent.com/56122898/68478759-97fb5600-0228-11ea-8167-053d4119be81.png)

The 6 compounds tested at human pharmacokinetic equivalent dosages were not platted on the same graph as above due to difference in concentrations which would make it rather difficult to compare the association between LogD and in vivo efficacy. It would be interesting to compare the trend for all azoles tested but I am unsure as to how to get around this issue in dosages difference, **suggestions** on this would be appreciated @wwjvdsande .
(Comment edited to include this from feedback received):
![image](https://user-images.githubusercontent.com/56122898/68517006-9dcf5680-027d-11ea-804f-98ca6272631a.png)

Following on from this, I would like to seek **suggestions** from this MycetOS community on what **molecules are able to penetrate this melanin structure** in the [grains](https://github.com/OpenSourceMycetoma/General-Start-Here/wiki/The-Challenge-of-the-Grains)??

**Comment by wwjvdsande** [comment]
Based on the data we have, amphotericin B is prolonging survival and should be able to penetrate. It was most potent. It gave a high percentage survival, even when used at different concentrations as tested above. @rosalynclz would it also be able to make an additional graph were the data is represented from the azoles and terbinafin and amphotericin B as well. it will not be too difficult to calculate the concentration in M. There will also be differences in activity. The activity is not only depending on grain penetration but also on protein binding. So the concentration of the compound actually reaching the grain will not always be the same. May be we should also look at fluorescent probes? Due to autofluorescence in green and red the probe needs to be blue . So coumarins or blue biodipy dies will also be excellent.

**Comment by MFernflower** [comment]
@wwjvdsande have you ever tried Butenafine? It's a bit smaller than lamisil and doesn't have that rigid triple bond in it.

**Comment by MFernflower** [comment]
Also the next batch of fenarimol analogs has a compound (MXF005) with a hydrocarbon tail on it so might be interesting to see what that will do!

@fantasy121 @wwjvdsande

**Comment by rosalynclz** [comment]
@wwjvdsande Just a quick question, about the red and green autofluorescence mentioned, is it known which structures in the fungi they belong to (e.g. green fluorescence of melanin?) ?

**Comment by wwjvdsande** [comment]
@rosalynclz as far as I know not. We observed it when we wanted to do immunofluorescence. In the end we ended up with using dyes where we don't need fluorescence. An example is seen below. This grain was not stained. Dapi was used to visualize the cells and an overlay was used. The green autofluorescence is clearly seen.

![39ctrlgrain 160x](https://user-images.githubusercontent.com/36398138/68948312-eb851b00-07b7-11ea-8827-2cfb08ed53be.gif)

**Comment by MFernflower** [comment]
@wwjvdsande <https://github.com/wwjvdsande> I have found that the gills of
certain mushroom species will glow the same shade of green when exposed to
a 365 nanometer LED source

**Comment by MFernflower** [comment]
@wwjvdsande @rosalynclz I have found that the gills of
certain mushroom species will glow the same shade of green when exposed to
a UV-A LED source

**Comment by MFernflower** [comment]
@wwjvdsande what was the excitation source?

**Comment by mattodd** [comment]
I finally uploaded Rosalyn Chan's very nice thesis that includes all this work - sorry for the delay and thanks to all those generous souls who helped Rosalyn with her calculations and ideas. The thesis is [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/blob/master/Theses%20Reports%20Docs/Rosalyn%20Chan%20UCL%202020/Rosalyn%20Chan%20MPharm%20Thesis%20UCL%20Pharmacy%202020.pdf) with a CC-BY licence. I'll close this issue and install a link to it on the wiki at https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Current-Targets-and-Activities so this discussion is not lost (in part because there is some nice discussion re fluorescence in this Issue).
